#!/bin/sh
set -e

case "$1" in
remove)
	update-alternatives --remove \
		u-boot-rk3576-axon-lite-idbloader \
		/usr/lib/u-boot/rk3576-axon-lite/idbloader.img

	update-alternatives --remove \
		u-boot-rk3576-axon-lite-uboot \
		/usr/lib/u-boot/rk3576-axon-lite/u-boot.img
	;;

failed-upgrade | deconfigure) ;;

*)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
